name: Test Rust Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run rust-release
        uses: xctions/release-rs@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
          platforms: linux-x86_64
