name: Test Rust Release

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run rust-release
        uses: xctions/rust-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ github.run_number }}
          platforms: linux-x86_64
